default:

  #
  # Basic
  #
  server:
    port: 8001

  #
  # Log
  #
  log:
    # path: maps.log

  #
  # Microservice
  #
  microservice:
    basePath: services
    server:
      name: geoservices/stakeholders/industry/v1
      # Add dependencies by uncommenting the line below
      #
      # dependencies: my/other/service/v1

  #
  # Zookeeper
  #
  zookeeper:
    connectionString: localhost:2181
    retry:
      wait: 1000
      count: 3

